### ISSUE TITLE
Zip File

### ISSUE THREAD

**Issue by lamarwatts** [davidmaillo/instagram-images-download-extension#1]
Ok after using this extension I must say that it needs to be able to download all the images in a zip file because my browser has been shut down 3 times after trying to download 95 photos which open 95 download windows and stop responding.

Thanks

**Comment by davidmaillo** [comment]
@lamarwatts Hey! Your feedback is very welcome! I will investigate about new methods to change the way that the browser downloads the files (i.e. make it able to select the output folder) and discover if it's possible to package in a zip.

How's the machine where you tested it, by the way? I have completed downloads greater than 200 images with success and no problems.

Thank you!!

**Comment by lamarwatts** [comment]
Thanks for getting back to me on this issue, my machine is great, I just
got it 2 months ago, I look forward to those improvements that would
benefit everyone that uses this extension.

Again Thank

[image: photo]
_Lamar A. Watts_
CEO, LAW Design House
360-208-0966 ext 201 | 360-772-8389 | contactme@lamarawatts.com |
https://lamarawatts.com
http://www.facebook.com/lawdesignhouse
http://twitter.com/lawdesignhouse  http://facebook.com/lamarawatts
http://www.linkedin.com/in/lamarawatts
Get a signature like this: Click here!
http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MDA4JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MzI1Njg1NDg3Njk3OTIiLCAiZSI6ICI1NzMyNTY4NTQ4NzY5NzkyIn0=&u=148959338539952

**Comment by davidmaillo** [comment]
Done! New version has the option for downloading as ZIP file 💃 ! It also downloads images with greater size and videos.

**Comment by lamarwatts** [comment]
You are awesome for doing that, I'm going to test it out and give you my feedback. Thanks and Happy New Year.

**Comment by lamarwatts** [comment]
Hey David to my feedback on paypal, once I add more money on my paypal account I'm going to donate to you for doing this feature and designing an awesome extension, also I want to share with you that you might want to give people another link to donate to you on paypal because everyone don't have a paypal account, I have that script if you want it, I use it for my clients all the time. Thanks

**Comment by davidmaillo** [comment]
Thanks @lamarwatts! I hope you enjoy the changes 👍 

What kind of link do you use for donations? You can contact me if you want: davidmaillo@me.com

**Comment by lamarwatts** [comment]
Check your email I sent you the paypal script, so here's my feedback on the instagram script, when I used it, it seem to work until I opened the zip file and only saw the first page of photos even though I did click the Load more button but then I choose the collect option and it collected all my photos and proved to be the best option to use, again awesome work. Also when I downloaded the files I had to convert them all to png just so I could open them in photoshop, it keep giving me an error message in photoshop with the jpg extension.
