### ISSUE TITLE
Extension broken

### ISSUE THREAD

**Issue by MrLuit** [davidmaillo/instagram-images-download-extension#2]
Instagram changed something on their backend and the project returns an 'invalid JSON' error on line 159

`Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.xhr.onreadystatechange (chrome-extension://pblgjchnlklkdkhcafceklibimpdfgbe/js/instagram.js:159)`

The extension is trying to reach and parse `https://www.instagram.com/<username>/?max_id=1` .

**Comment by MrLuit** [comment]
To be clear; Only the ZIP function doesn't work. If you uncheck 'Download as ZIP' the images download just fine.

**Comment by davidmaillo** [comment]
Thanks for reporting! I will take a look.

**Comment by ViggoZ** [comment]
can not work?

**Comment by davidmaillo** [comment]
If anyone has detected what's going on and achieved a working result, please make a pull request so I can apply the changes on this repository. Thanks!
